export { MainPage } from './MainPage'
export { LoginPage } from './LoginPage/LoginPage'
export { RegistrationPage } from './RegistrationPage'
export { GamePage } from './GamePage/GamePage'
export { GameOverPage } from './GameOverPage'
export { LidersPage } from './LidersPage'
export { ForumMainPage } from './ForumMainPage'
export { ForumTopicPage } from './ForumTopicPage'
export { ServerErrorPage } from './ServerErrorPage'
export { NotFoundPage } from './NotFoundPage'

export * from './Profile'
export * from './ProfileEdit'
export * from './ProfilePassword'
export * from './EditAvatar'
