export { MainPage } from './MainPage'
export { LoginPage } from './Login/LoginPage'
export { RegistrationPage } from './RegistrationPage'
export { GamePage } from './GamePage'
export { GameOverPage } from './GameOverPage'
export { LidersPage } from './LidersPage'
export { ForumMainPage } from './ForumMainPage'
export { ForumTopicPage } from './ForumTopicPage'
export { ErrorPage } from './ErrorPage'
export { NotFoundPage } from './NotFoundPage'

export * from './Profile'
export * from './ProfileEdit'
export * from './ProfilePassword'
